"""honest_paper

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-14 23:28:30.007384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: Union[str, Sequence[str], None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("first_tick_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_tick_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candles")),
        sa.UniqueConstraint(
            "symbol", "exchange", "interval", "source", "ts", name=op.f("uq_candles_symbol")
        ),
        if_not_exists=True,
    )
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_backtest_runs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_backtest_runs_user_id"),
        "backtest_runs",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "holdings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("broker_account_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_holdings_broker_account_id_broker_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holdings")),
        sa.UniqueConstraint(
            "broker_account_id", "symbol", "exchange", name=op.f("uq_holdings_broker_account_id")
        ),
        if_not_exists=True,
    )
    op.create_table(
        "cash_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("broker_account_id", sa.UUID(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fill_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_cash_ledger_broker_account_id_broker_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["fill_id"], ["fills.id"], name=op.f("fk_cash_ledger_fill_id_fills")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_ledger")),
        sa.UniqueConstraint("fill_id", "entry_type", name=op.f("uq_cash_ledger_fill_id")),
        if_not_exists=True,
    )
    op.create_index(
        "ix_cash_ledger_account_id",
        "cash_ledger",
        ["broker_account_id", "id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "pending_settlements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("broker_account_id", sa.UUID(), nullable=False),
        sa.Column("fill_id", sa.UUID(), nullable=True),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("settles_on", sa.Date(), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_pending_settlements_broker_account_id_broker_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["fill_id"], ["fills.id"], name=op.f("fk_pending_settlements_fill_id_fills")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_settlements")),
        sa.UniqueConstraint("fill_id", name=op.f("uq_pending_settlements_fill_id")),
        if_not_exists=True,
    )
    op.create_index(
        "ix_settlements_due",
        "pending_settlements",
        ["settles_on", "broker_account_id"],
        unique=False,
        if_not_exists=True,
    )
    # 0007 creates this index; reflect it in metadata and repair databases
    # bootstrapped directly from the older metadata as well.
    op.create_index(
        "ix_recovery_codes_user_id", "recovery_codes", ["user_id"], unique=False, if_not_exists=True
    )
    # Seed cash from the latest broker snapshot, preserving existing balances.
    op.execute("""
        INSERT INTO cash_ledger (broker_account_id, ts, entry_type, amount, balance)
        SELECT a.id, now(), 'OPENING', COALESCE(f.available_cash, 1000000),
               COALESCE(f.available_cash, 1000000)
        FROM broker_accounts a
        LEFT JOIN LATERAL (
            SELECT available_cash FROM funds_snapshots WHERE broker_account_id=a.id
            ORDER BY ts DESC, id DESC LIMIT 1
        ) f ON true
        WHERE a.environment='paper'
          AND NOT EXISTS (SELECT 1 FROM cash_ledger c WHERE c.broker_account_id=a.id)
    """)
    # Existing CNC inventory has no trustworthy settlement provenance. Carry it
    # as pending for one session from upgrade, rather than invent settled stock.
    from datetime import datetime
    import uuid
    from app.domain.calendar import IST, settlement_date

    conn = op.get_bind()
    legacy = (
        conn.execute(
            sa.text("""
        SELECT * FROM positions WHERE environment='paper' AND product='CNC' AND quantity != 0
    """)
        )
        .mappings()
        .all()
    )
    if any(row["quantity"] < 0 for row in legacy):
        raise RuntimeError("Reset legacy paper CNC short positions before migration 0008")
    if legacy:
        due = settlement_date(datetime.now(IST).date())
        for row in legacy:
            conn.execute(
                sa.text("""
                INSERT INTO pending_settlements
                (id, broker_account_id, symbol, exchange, quantity, price, settles_on)
                VALUES (:id, :account, :symbol, :exchange, :quantity, :price, :due)
            """),
                dict(
                    id=uuid.uuid4(),
                    account=row["broker_account_id"],
                    symbol=row["symbol"],
                    exchange=row["exchange"],
                    quantity=row["quantity"],
                    price=row["average_price"],
                    due=due,
                ),
            )
    op.execute("""
        CREATE OR REPLACE FUNCTION cash_ledger_immutable() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'cash_ledger is append-only'; END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("DROP TRIGGER IF EXISTS cash_ledger_immutable ON cash_ledger")
    op.execute("""
        CREATE TRIGGER cash_ledger_immutable BEFORE UPDATE OR DELETE ON cash_ledger
        FOR EACH ROW EXECUTE FUNCTION cash_ledger_immutable()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_settlements_due", table_name="pending_settlements")
    op.drop_table("pending_settlements")
    op.drop_index("ix_cash_ledger_account_id", table_name="cash_ledger")
    op.drop_table("cash_ledger")
    op.execute("DROP FUNCTION IF EXISTS cash_ledger_immutable()")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_backtest_runs_user_id"), table_name="backtest_runs")
    op.drop_table("backtest_runs")
    op.drop_table("candles")
    # ### end Alembic commands ###
